### ISSUE TITLE
Formulario de registro en falta

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-01#13]
Independientemente de la forma en la que busquen resolver que el usuario pueda registrarse en su sitio, aún no hay un formulario dedicado a ello. 
Esto ya era una prioridad pasado el sprint 2 incompleto, ahora es algo que necesitan hacer cuanto antes.

**Comment by Danirodri0201** [comment]
Buenas tardes! Habíamos elegido hacerlo como un pop-up con el formulario, el mismo se encuentra en un partial que es llamado en el index pero si es mas conveniente realizarlo como vista lo corregimos enseguida. Saludos!

**Comment by saimon2989** [comment]
Hola! Favor revisar este issue que ya esta solucionado! Gracias!
