### ISSUE TITLE
Nuevas páginas inexistentes

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-01#14]
Si bien se merodeó la posibilidad de que las páginas de creación, edición y listado de productos pudieran ser entre opcionales y obligatorias, se especificó el hecho de que iban a necesitarlas indispensablemente para el cuarto sprint.
Las páginas actualmente no existen (ni sus respectivas rutas/controladores), por lo que tendrán que sumarlas a la lista de cosas para hacer antes de poder continuar con el resto.

**Comment by JeremiasCastillo25** [comment]
Comento que ellos tienen actualmente el register en un pop-up en el header.
De igual manera les recomendé que tengan una vista particular para la misma.

**Comment by saimon2989** [comment]
Hola! Por favor revisar este issue, ya se encuentran las paginas creadas.
