### ISSUE TITLE
Trello

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-01#15]
El tablero de trabajo, como una herramienta organizativa, es realmente muy útil e importante.
Traten de mantenerlo actualizado con cada cambio que vayan haciendo, siendo esto algo que trasciende a las iteraciones: Si hay nuevas iteraciones, las tareas cambian completamente y debe haber un tablero que les ayude a organizarse (además de que también sirve como reflejo de su trabajo)

**Comment by saimon2989** [comment]
Hola ! Por favor revisar este issue, ya se encuentra el tablero de Trello actualizado con las tareas!
