### ISSUE TITLE
Cuál es el sentido de esta ruta?

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-01#21]
No cubren esto casos con los middlewares? Parece como que les quedó de antes y se olvidaron de borrarla

https://github.com/0623CIFSNCN05LAED/grupo-01/blob/7012471763401ed29d51ea8594ca7775be138ff2/src/routers/users.js#L35-L42

**Comment by DupuyAle** [comment]
era chequear si se guardaba la informacion cuando implementabamos session, ya se corrigio
