### ISSUE TITLE
res.render en post

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-01#22]
Este controlador, y lo mismo pasa en el register no debería tener un render ya que viene de una ruta post. Debería ser un redirect con flash errors

https://github.com/0623CIFSNCN05LAED/grupo-01/blob/7012471763401ed29d51ea8594ca7775be138ff2/src/controllers/user-controller.js#L76-L84

**Comment by DupuyAle** [comment]
ya se cambio a todos los metodos POST de res.render a res.redirect
