### ISSUE TITLE
nodemon

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-01#3]
Les sugiero fuertemente, especialmente ahora que vamos a empezar a modificar más los js, que instalen y utilicen un script que tenga nodemon (además del que ya tienen)

https://github.com/0623CIFSNCN05LAED/grupo-01/blob/5ea757c17daaf599d0a3c845b79ce36b48dea510/package.json#L8

**Comment by Danirodri0201** [comment]
Buenas tardes profe!
Se incluye nodemon
https://github.com/0623CIFSNCN05LAED/grupo-01/blob/2c44c1d2b4a7335b110b10b3274fa4368de04280/package.json#L9
