### ISSUE TITLE
Ruta inexistente

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-01#4]
Esta ruta no tiene sentido (y su respectivo link) si van a usar un pop-up... a decidir por cuál opción van

https://github.com/0623CIFSNCN05LAED/grupo-01/blob/5ea757c17daaf599d0a3c845b79ce36b48dea510/src/app.js#L15-L17

**Comment by Danirodri0201** [comment]
Buenas tardes profe!
Se borra línea innecesaria por el momento.
