### ISSUE TITLE
Orden de imports css

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-01#5]
Sus imports deberían ser los últimos. Siempre conviene ir de lo más general a lo más específico

https://github.com/0623CIFSNCN05LAED/grupo-01/blob/5ea757c17daaf599d0a3c845b79ce36b48dea510/src/view/index.html#L6-L11

**Comment by Danirodri0201** [comment]
Buenas tardes profe, se ordenan imports css
https://github.com/0623CIFSNCN05LAED/grupo-01/blob/2c44c1d2b4a7335b110b10b3274fa4368de04280/src/views/index.html#L7-L11
