### ISSUE TITLE
Form action

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-01#6]
El action debería ser la ruta que procesa este form. Ya lo vamos a ver en las próximas calses, se los digo para que quede tageado. 

https://github.com/0623CIFSNCN05LAED/grupo-01/blob/5ea757c17daaf599d0a3c845b79ce36b48dea510/src/view/index.html#L140

**Comment by Danirodri0201** [comment]
Action ok
