### ISSUE TITLE
nombres de archivos mejor en minúscula

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-01#7]
Les sugiero, para ahorrarse dolores de cabeza por cambios de OS que siempre tengan los nombres de archivos, incluidas las imágenes en minúscula

https://github.com/0623CIFSNCN05LAED/grupo-01/blob/5ea757c17daaf599d0a3c845b79ce36b48dea510/src/view/login.html#L15

**Comment by Danirodri0201** [comment]
Buenas tardes profe!
Se corrige nombre de archivo a minúscula y se tendrá en cuenta para los futuros incluidos.

**Comment by Danirodri0201** [comment]
Buenas noches profe, se dejan nombres de archivos en minúsculas.
