### ISSUE TITLE
Idioma del sitio

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-01#8]
Más que nada para traductores y SEO, que no es un detalle. 

https://github.com/0623CIFSNCN05LAED/grupo-01/blob/5ea757c17daaf599d0a3c845b79ce36b48dea510/src/view/index.html#L2

**Comment by Danirodri0201** [comment]
Buenas tardes profe, se deja en español
[<html lang="es">](https://github.com/0623CIFSNCN05LAED/grupo-01/blob/2c44c1d2b4a7335b110b10b3274fa4368de04280/src/views/login.html#L2)
