### ISSUE TITLE
Evitar console logs en código productivo

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-01#9]
No hay problema en sus ramas pero una vez que lo van a pasar a main y por lo tanto a lo que ve el usuario mejor sacarlos

https://github.com/0623CIFSNCN05LAED/grupo-01/blob/5ea757c17daaf599d0a3c845b79ce36b48dea510/public/js/index.js#L41

**Comment by Danirodri0201** [comment]
Buenas tardes profe, se elimina el console.log
